### ISSUE TITLE
Machine-readable/plaintext version?

### ISSUE THREAD

**Issue by tjg** [openrtb/OpenRTB#12]
Hi!

Is there a machine-readable or plaintext version of the spec, or should I parse the PDF?

(My goal is to decrease implementation time and increase correctness.)

**Comment by soylent** [comment]
You can find JSON schemas for bid request and response objects here
https://github.com/openrtb/openrtb2x/tree/0c581493b172862f4f92e1829c79f74f3a068ba7/openrtb-validator/src/main/resources/schemas

I would suggest developers of the standard to publish these schema files, so that anyone could easily use them. Any DSP or SSP implementation probably will need the schema files. It would be great if I could do something like this:
```
json_schema = JSONSchema.new('$ref' => 'http://example.com/bid-request-2.2.json')
json_schema.validate(bid_request_json)
```

**Comment by lpgauth** [comment]
official schemas would be great! :+1:

**Comment by markhu** [comment]
I'd like to see the OpenRTB spec in MarkDown format, so we could see it rendered right here on GitHub. The formatting is not terribly complex, but at 80 pages containing 25 tables, converting it isn't a quick afternoon project either.

**Comment by samtingleff** [comment]
We've moved to markdown in ORTB 3. Closing!
